# Generated by Django 5.0.1 on 2024-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roles', models.JSONField()),
                ('region', models.CharField(max_length=100)),
                ('releasedYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelMap', models.JSONField(default=dict, help_text='Dictionary of inputted champions & Role/Region labels')),
            ],
        ),
    ]
