# Generated by Django 5.0.1 on 2024-03-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loldoku', '0002_alter_championinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='championinfo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
